### ISSUE TITLE
Clashes with firestick default commands

### ISSUE THREAD

**Issue by thatmodelguy** [kodi-connect/kodi-alexa-video#22]
There's probably nothing that can be done about this since the firestick commands override these ones but I figured I would report it in case this app goes official. When giving commands with kodi open the default commands automatically take over and switch from kodi to the default browser for playback and search results. It would seem the only way around this would be in the option to tell alexa to open kodi commands and then control it from there.It would be awesome if they could work together
On a side note, this is an awesome program and works very well. It would really benefit to have some navigation commands such as these if it was doable:
go left
go right
go up
go down
Select
Go back
Cancel
Main menu

**Comment by mike123yy** [comment]
I can see the navigation controls being somewhat pointless for the average user but for someone like myself it would save a bit of hassle. A lot of people taking advantage of the voice activated software's do so out of necessity. I'm paralyzed from the chest down so using a remote is kind of a pain. The cancel and select function would be helpful for any one though. For example, if you're playing a movie from your library that is from a add on and you get an error message a popup window will appear that will stop the other voice commands from functioning until you close the window. Then you have to get up and close the window manually or search for the remote. It may sound kind of trivial but the point of using the speech recognition is so you can talk to the machine rather than do it yourself. Anyway, that's my 2 cents.

**Comment by tkislan** [comment]
Then I would suggest this skill:
https://github.com/m0ngr31/kanzi
