### ISSUE TITLE
Cannot link devices

### ISSUE THREAD

**Issue by broyuken** [kodi-connect/kodi-alexa-video#33]
I have everything all set up, it's connected to the service and everything. I tried to link the skill with my echo dot, but when I try the list of connected devices always comes back empty.

**Comment by DaJansenGit** [comment]
just set up the skill, same issue for me

**Comment by tkislan** [comment]
And is your content country in Amazon account set to either US/UK/DE?

**Comment by joes01** [comment]
Thomas, having same issue.Any idea why? my content country is set to US.

**Comment by MEIJE942** [comment]
Hi Thomas, the same here.. It was working on my android box but the linked devices are not visible anymore. 
Also linking a new device is not working. 
My echo and echo dot are on an US account. (and as mentioned, did function in the past)

**Comment by ChrisCoxon29** [comment]
Having the same issue here since starting the new beta run.

**Comment by tkislan** [comment]
This is most likely an issue with Alexa app, because even if it doesn’t show any linked devices, it still works for me.
Can you confirm, that you can invoke Alexa, and that it indeed starts playback for you?

**Comment by ChrisCoxon29** [comment]
Yeah it all works fine, just always shows no linked devices.

Sent from my iPhone

On 20 Nov 2018, at 14:20, Tomas Kislan <notifications@github.com<mailto:notifications@github.com>> wrote:


This is most likely an issue with Alexa app, because even if it doesn’t show any linked devices, it still works for me.
Can you confirm, that you can invoke Alexa, and that it indeed starts playback for you?
